# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleMapDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleMapDemo
	pod 'GoogleMaps', '3.1.0'
  	pod 'GooglePlaces', '3.1.0'
  target 'GoogleMapDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoogleMapDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
